// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package gokoreanbots

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6601e8cdDecodeGithubComGokoreanbotsGokoreanbots(in *jlexer.Lexer, out *Vote) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "voted":
			out.Voted = bool(in.Bool())
		case "lastVote":
			out.LastVote = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComGokoreanbotsGokoreanbots(out *jwriter.Writer, in Vote) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"voted\":"
		out.RawString(prefix[1:])
		out.Bool(bool(in.Voted))
	}
	{
		const prefix string = ",\"lastVote\":"
		out.RawString(prefix)
		out.Int64(int64(in.LastVote))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Vote) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComGokoreanbotsGokoreanbots(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Vote) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComGokoreanbotsGokoreanbots(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Vote) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComGokoreanbotsGokoreanbots(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Vote) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComGokoreanbotsGokoreanbots(l, v)
}
func easyjson6601e8cdDecodeGithubComGokoreanbotsGokoreanbots1(in *jlexer.Lexer, out *RawResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "code":
			out.Code = int(in.Int())
		case "data":
			(out.Data).UnmarshalEasyJSON(in)
		case "version":
			out.Version = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComGokoreanbotsGokoreanbots1(out *jwriter.Writer, in RawResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"code\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Code))
	}
	{
		const prefix string = ",\"data\":"
		out.RawString(prefix)
		(in.Data).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"version\":"
		out.RawString(prefix)
		out.Int(int(in.Version))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RawResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComGokoreanbotsGokoreanbots1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RawResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComGokoreanbotsGokoreanbots1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RawResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComGokoreanbotsGokoreanbots1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RawResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComGokoreanbotsGokoreanbots1(l, v)
}
func easyjson6601e8cdDecodeGithubComGokoreanbotsGokoreanbots2(in *jlexer.Lexer, out *Bots) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "type":
			out.Type = string(in.String())
		case "data":
			if in.IsNull() {
				in.Skip()
				out.Data = nil
			} else {
				in.Delim('[')
				if out.Data == nil {
					if !in.IsDelim(']') {
						out.Data = make([]Bot, 0, 0)
					} else {
						out.Data = []Bot{}
					}
				} else {
					out.Data = (out.Data)[:0]
				}
				for !in.IsDelim(']') {
					var v1 Bot
					(v1).UnmarshalEasyJSON(in)
					out.Data = append(out.Data, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "currentPage":
			out.CurrentPage = int(in.Int())
		case "totalPage":
			out.TotalPage = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComGokoreanbotsGokoreanbots2(out *jwriter.Writer, in Bots) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"data\":"
		out.RawString(prefix)
		if in.Data == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Data {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"currentPage\":"
		out.RawString(prefix)
		out.Int(int(in.CurrentPage))
	}
	{
		const prefix string = ",\"totalPage\":"
		out.RawString(prefix)
		out.Int(int(in.TotalPage))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Bots) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComGokoreanbotsGokoreanbots2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Bots) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComGokoreanbotsGokoreanbots2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Bots) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComGokoreanbotsGokoreanbots2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Bots) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComGokoreanbotsGokoreanbots2(l, v)
}
func easyjson6601e8cdDecodeGithubComGokoreanbotsGokoreanbots3(in *jlexer.Lexer, out *BotStatRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "servers":
			out.Servers = int(in.Int())
		case "shards":
			out.Shards = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComGokoreanbotsGokoreanbots3(out *jwriter.Writer, in BotStatRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"servers\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Servers))
	}
	{
		const prefix string = ",\"shards\":"
		out.RawString(prefix)
		out.Int(int(in.Shards))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v BotStatRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComGokoreanbotsGokoreanbots3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BotStatRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComGokoreanbotsGokoreanbots3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BotStatRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComGokoreanbotsGokoreanbots3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BotStatRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComGokoreanbotsGokoreanbots3(l, v)
}
func easyjson6601e8cdDecodeGithubComGokoreanbotsGokoreanbots4(in *jlexer.Lexer, out *BotOwner) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.Id = string(in.String())
		case "flags":
			out.Flags = int(in.Int())
		case "github":
			out.Github = string(in.String())
		case "tag":
			out.Tag = string(in.String())
		case "username":
			out.Username = string(in.String())
		case "bots":
			if in.IsNull() {
				in.Skip()
				out.Bots = nil
			} else {
				in.Delim('[')
				if out.Bots == nil {
					if !in.IsDelim(']') {
						out.Bots = make([]string, 0, 4)
					} else {
						out.Bots = []string{}
					}
				} else {
					out.Bots = (out.Bots)[:0]
				}
				for !in.IsDelim(']') {
					var v4 string
					v4 = string(in.String())
					out.Bots = append(out.Bots, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComGokoreanbotsGokoreanbots4(out *jwriter.Writer, in BotOwner) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.Id))
	}
	{
		const prefix string = ",\"flags\":"
		out.RawString(prefix)
		out.Int(int(in.Flags))
	}
	{
		const prefix string = ",\"github\":"
		out.RawString(prefix)
		out.String(string(in.Github))
	}
	{
		const prefix string = ",\"tag\":"
		out.RawString(prefix)
		out.String(string(in.Tag))
	}
	{
		const prefix string = ",\"username\":"
		out.RawString(prefix)
		out.String(string(in.Username))
	}
	{
		const prefix string = ",\"bots\":"
		out.RawString(prefix)
		if in.Bots == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.Bots {
				if v5 > 0 {
					out.RawByte(',')
				}
				out.String(string(v6))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v BotOwner) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComGokoreanbotsGokoreanbots4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BotOwner) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComGokoreanbotsGokoreanbots4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BotOwner) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComGokoreanbotsGokoreanbots4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BotOwner) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComGokoreanbotsGokoreanbots4(l, v)
}
func easyjson6601e8cdDecodeGithubComGokoreanbotsGokoreanbots5(in *jlexer.Lexer, out *Bot) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.Id = string(in.String())
		case "flags":
			out.Flags = int(in.Int())
		case "owners":
			if in.IsNull() {
				in.Skip()
				out.Owners = nil
			} else {
				in.Delim('[')
				if out.Owners == nil {
					if !in.IsDelim(']') {
						out.Owners = make([]BotOwner, 0, 0)
					} else {
						out.Owners = []BotOwner{}
					}
				} else {
					out.Owners = (out.Owners)[:0]
				}
				for !in.IsDelim(']') {
					var v7 BotOwner
					(v7).UnmarshalEasyJSON(in)
					out.Owners = append(out.Owners, v7)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "lib":
			out.Library = string(in.String())
		case "prefix":
			out.Prefix = string(in.String())
		case "votes":
			out.Votes = int(in.Int())
		case "servers":
			out.Servers = int(in.Int())
		case "intro":
			out.Intro = string(in.String())
		case "desc":
			out.Description = string(in.String())
		case "web":
			out.Web = string(in.String())
		case "git":
			out.Git = string(in.String())
		case "url":
			out.Url = string(in.String())
		case "category":
			if in.IsNull() {
				in.Skip()
				out.Category = nil
			} else {
				in.Delim('[')
				if out.Category == nil {
					if !in.IsDelim(']') {
						out.Category = make([]string, 0, 4)
					} else {
						out.Category = []string{}
					}
				} else {
					out.Category = (out.Category)[:0]
				}
				for !in.IsDelim(']') {
					var v8 string
					v8 = string(in.String())
					out.Category = append(out.Category, v8)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "status":
			out.Status = string(in.String())
		case "discord":
			out.Discord = string(in.String())
		case "state":
			out.State = string(in.String())
		case "vanity":
			out.Vanity = string(in.String())
		case "bg":
			out.Background = string(in.String())
		case "banner":
			out.Banner = string(in.String())
		case "tag":
			out.Tag = string(in.String())
		case "avatar":
			out.Avatar = string(in.String())
		case "name":
			out.Name = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComGokoreanbotsGokoreanbots5(out *jwriter.Writer, in Bot) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.Id))
	}
	{
		const prefix string = ",\"flags\":"
		out.RawString(prefix)
		out.Int(int(in.Flags))
	}
	{
		const prefix string = ",\"owners\":"
		out.RawString(prefix)
		if in.Owners == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v9, v10 := range in.Owners {
				if v9 > 0 {
					out.RawByte(',')
				}
				(v10).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"lib\":"
		out.RawString(prefix)
		out.String(string(in.Library))
	}
	{
		const prefix string = ",\"prefix\":"
		out.RawString(prefix)
		out.String(string(in.Prefix))
	}
	{
		const prefix string = ",\"votes\":"
		out.RawString(prefix)
		out.Int(int(in.Votes))
	}
	{
		const prefix string = ",\"servers\":"
		out.RawString(prefix)
		out.Int(int(in.Servers))
	}
	{
		const prefix string = ",\"intro\":"
		out.RawString(prefix)
		out.String(string(in.Intro))
	}
	{
		const prefix string = ",\"desc\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	{
		const prefix string = ",\"web\":"
		out.RawString(prefix)
		out.String(string(in.Web))
	}
	{
		const prefix string = ",\"git\":"
		out.RawString(prefix)
		out.String(string(in.Git))
	}
	{
		const prefix string = ",\"url\":"
		out.RawString(prefix)
		out.String(string(in.Url))
	}
	{
		const prefix string = ",\"category\":"
		out.RawString(prefix)
		if in.Category == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v11, v12 := range in.Category {
				if v11 > 0 {
					out.RawByte(',')
				}
				out.String(string(v12))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"discord\":"
		out.RawString(prefix)
		out.String(string(in.Discord))
	}
	{
		const prefix string = ",\"state\":"
		out.RawString(prefix)
		out.String(string(in.State))
	}
	{
		const prefix string = ",\"vanity\":"
		out.RawString(prefix)
		out.String(string(in.Vanity))
	}
	{
		const prefix string = ",\"bg\":"
		out.RawString(prefix)
		out.String(string(in.Background))
	}
	{
		const prefix string = ",\"banner\":"
		out.RawString(prefix)
		out.String(string(in.Banner))
	}
	{
		const prefix string = ",\"tag\":"
		out.RawString(prefix)
		out.String(string(in.Tag))
	}
	{
		const prefix string = ",\"avatar\":"
		out.RawString(prefix)
		out.String(string(in.Avatar))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Bot) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComGokoreanbotsGokoreanbots5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Bot) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComGokoreanbotsGokoreanbots5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Bot) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComGokoreanbotsGokoreanbots5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Bot) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComGokoreanbotsGokoreanbots5(l, v)
}
